### ISSUE TITLE
Capture all stdout/stderr output

### ISSUE THREAD

**Issue by PFython** [PFython/easypypi#3]
start_gui(redirect=True) captures some but not all output currently... e.g. the output from running setup.py, twine, and pip.

I'm not familiar enough with PySimpleGUI and generally handling stdout/stderr to solve this on my own I'm afraid...

**Comment by salabim** [comment]
Instead of using os.system(), use subprocess.Popen or subprocess.call(), which has parameters to capture the generated output.
Like (from my simply_black project):

    sp = subprocess.Popen(
        [
            black_bin,
            *linelength_param,
            *target_param,
            *skip_string_normalization_param,
            *selection,
        ],
        shell=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    out, err = sp.communicate()
    result = "".join(c for c in err.decode("utf-8") if ord(c) < 255)

Note that the output (in this case in result) is only available after the process has ended. I haven't found a way to dynamically output to a window.

**Comment by PFython** [comment]
For simplicity, I've decided to remove this redirection feature for now.
